/*
 * META Core Hardware Configuration.
 *
 * Copyright (C) 2011 Imagination Technologies Ltd.
 */

#ifndef meta_core_config_h
# define meta_core_config_h "core_config.h"

#define META_CORECFG_CACHE_TYPE_S       0
#define META_CORECFG_CACHE_TYPE_M       (0x7 << META_CORECFG_CACHE_TYPE_S)
#define META_CORECFG_CACHE_TYPE_FULL        (0 << META_CORECFG_CACHE_TYPE_S)
#define META_CORECFG_CACHE_TYPE_NOMMU       (1 << META_CORECFG_CACHE_TYPE_S)
#define META_CORECFG_CACHE_TYPE_NOCACHE     (2 << META_CORECFG_CACHE_TYPE_S)
#define META_CORECFG_DSP_TYPE_S         3
#define META_CORECFG_DSP_TYPE_M         (0x7 << META_CORECFG_DSP_TYPE_S)
#define META_CORECFG_DSP_TYPE_FULL          (0 << META_CORECFG_DSP_TYPE_S)
#define META_CORECFG_DSP_TYPE_REDUCED       (1 << META_CORECFG_DSP_TYPE_S)
#define META_CORECFG_DSP_ACC_S          6
#define META_CORECFG_FPU_ACC_M          (0x1 << META_CORECFG_DSP_ACC_S)
#define META_CORECFG_FPU_ACC_FULL           (0 << META_CORECFG_DSP_ACC_S)
#define META_CORECFG_FPU_ACC_NONE           (1 << META_CORECFG_DSP_ACC_S)
#define META_CORECFG_FPU_TYPE_S         7
#define META_CORECFG_FPU_TYPE_M         (0x3 << META_CORECFG_FPU_TYPE_S)
#define META_CORECFG_FPU_TYPE_FULL          (0 << META_CORECFG_FPU_TYPE_S)
#define META_CORECFG_FPU_TYPE_SINGLE        (1 << META_CORECFG_FPU_TYPE_S)
#define META_CORECFG_AMA_TYPE_S         9
#define META_CORECFG_AMA_TYPE_M         (0x1 << META_CORECFG_AMA_TYPE_S)
#define META_CORECFG_AMA_TYPE_FULL          (0 << META_CORECFG_AMA_TYPE_S)
#define META_CORECFG_AMA_TYPE_REDUCED       (1 << META_CORECFG_AMA_TYPE_S)
#define META_CORECFG_GLB_CACHE_COH_S    10
#define META_CORECFG_GLB_CACHE_COH_M    (0x1 << META_CORECFG_GLB_CACHE_COH_S)
#define META_CORECFG_GLB_CACHE_COH_FULL     (0 << META_CORECFG_GLB_CACHE_COH_S)
#define META_CORECFG_GLB_CACHE_COH_NONE     (1 << META_CORECFG_GLB_CACHE_COH_S)

#define META_CORECFG2_BRKPOINTS_S       0
#define META_CORECFG2_BRKPOINTS_M       (0x2 << META_CORECFG2_BRKPOINTS_S)
#define META_CORECFG2_BRKPOINTS_0           (0 << META_CORECFG2_BRKPOINTS_S)
#define META_CORECFG2_BRKPOINTS_2           (1 << META_CORECFG2_BRKPOINTS_S)
#define META_CORECFG2_BRKPOINTS_4           (2 << META_CORECFG2_BRKPOINTS_S)
#define META_CORECFG2_BRKPOINTS_8           (3 << META_CORECFG2_BRKPOINTS_S)
#define META_CORECFG2_WTCHPOINTS_S      2
#define META_CORECFG2_WTCHPOINTS_M      (0x2 << META_CORECFG2_WTCHPOINTS_S)
#define META_CORECFG2_WTCHPOINTS_0          (0 << META_CORECFG2_WTCHPOINTS_S)
#define META_CORECFG2_WTCHPOINTS_2          (1 << META_CORECFG2_WTCHPOINTS_S)
#define META_CORECFG2_WTCHPOINTS_4          (2 << META_CORECFG2_WTCHPOINTS_S)
#define META_CORECFG2_WTCHPOINTS_8          (3 << META_CORECFG2_WTCHPOINTS_S)
#define META_CORECFG2_RTT_S             4
#define META_CORECFG2_RTT_M             (0x1 << META_CORECFG2_RTT_S)
#define META_CORECFG2_RTT_FULL              (0 << META_CORECFG2_RTT_S)
#define META_CORECFG2_RTT_NONE              (1 << META_CORECFG2_RTT_S)
#define META_CORECFG2_GBL_AU_S          5
#define META_CORECFG2_GBL_AU_M          (0x7 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_AU_0              (0 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_AU_1              (1 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_AU_2              (2 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_AU_4              (3 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_AU_8              (4 << META_CORECFG2_GBL_AU_S)
#define META_CORECFG2_GBL_DU_S          8
#define META_CORECFG2_GBL_DU_M          (0x7 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_0              (0 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_1              (1 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_2              (2 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_4              (3 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_8              (4 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_DU_16             (5 << META_CORECFG2_GBL_DU_S)
#define META_CORECFG2_GBL_ACC_S         11
#define META_CORECFG2_GBL_ACC_M         (0x3 << META_CORECFG2_GBL_ACC_S)
#define META_CORECFG2_ICACHE_SIZE_S     13
#define META_CORECFG2_ICACHE_SIZE_M     (0x7 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_DCACHE_SIZE_S     16
#define META_CORECFG2_DCACHE_SIZE_M     (0x7 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_ICACHE_SIZE_NP_S  19
#define META_CORECFG2_ICACHE_SIZE_NP_M  (0x7 << META_CORECFG2_ICACHE_SIZE_NP_S)
#define META_CORECFG2_DCACHE_SIZE_NP_S  22
#define META_CORECFG2_DCACHE_SIZE_NP_M  (0x7 << META_CORECFG2_DCACHE_SIZE_NP_S)
#define META_CORECFG2_ICACHE_SMALL_S    25
#define META_CORECFG2_ICACHE_SMALL_M    (0x1 << META_CORECFG2_ICACHE_SMALL_S)
#define META_CORECFG2_DCACHE_SMALL_S    26
#define META_CORECFG2_DCACHE_SMALL_M    (0x1 << META_CORECFG2_DCACHE_SMALL_S)
#define META_CORECFG2_DCACHE_WB_S       27
#define META_CORECFG2_DCACHE_WB_M       (0x1 << META_CORECFG2_DCACHE_WB_S)
#define META_CORECFG2_SEG_MMU_S         28
#define META_CORECFG2_SEG_MMU_M         (0x1 << META_CORECFG2_SEG_MMU_S)
#define META_CORECFG2_BASELINE_DSP_S    31
#define META_CORECFG2_BASELINE_DSP_M    (0x1 << META_CORECFG2_BASELINE_DSP_S)

#define META_CORECFG2_ICACHE_64B        ((0 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_128B       ((1 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_256B       ((2 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_512B       ((3 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_1K         ((4 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_2K         ((5 << META_CORECFG2_ICACHE_SIZE_S) | \
                                            META_CORECFG2_ICACHE_SMALL_M)
#define META_CORECFG2_ICACHE_4K         (0 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_ICACHE_8K         (1 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_ICACHE_16K        (2 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_ICACHE_32K        (3 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_ICACHE_64K        (4 << META_CORECFG2_ICACHE_SIZE_S)
#define META_CORECFG2_ICACHE_128K       (5 << META_CORECFG2_ICACHE_SIZE_S)

#define META_CORECFG2_DCACHE_64B        ((0 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_128B       ((1 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_256B       ((2 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_512B       ((3 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_1K         ((4 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_2K         ((5 << META_CORECFG2_DCACHE_SIZE_S) | \
                                            META_CORECFG2_DCACHE_SMALL_M)
#define META_CORECFG2_DCACHE_4K         (0 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_DCACHE_8K         (1 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_DCACHE_16K        (2 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_DCACHE_32K        (3 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_DCACHE_64K        (4 << META_CORECFG2_DCACHE_SIZE_S)
#define META_CORECFG2_DCACHE_128K       (5 << META_CORECFG2_DCACHE_SIZE_S)

#define META_CORECFG(CFG, FLD) \
    (((CFG2) & META_CORECFG_##FLD##_M) >> META_CORECFG_##FLD##_S)
#define META_CORECFG2(CFG2, FLD) \
    (((CFG2) & META_CORECFG2_##FLD##_M) >> META_CORECFG2_##FLD##_S)

#endif
